# Generated by Django 4.2 on 2023-05-21 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ao',
            fields=[
                ('id_ao', models.AutoField(primary_key=True, serialize=False)),
                ('ten_ao', models.CharField(max_length=100)),
                ('soluong', models.IntegerField()),
                ('giatien', models.DecimalField(decimal_places=3, max_digits=30)),
                ('mo_ta', models.TextField()),
                ('anh', models.CharField(max_length=250)),
                ('anh_lq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='USER.loaianh')),
            ],
        ),
    ]
