# Generated by Django 4.2 on 2023-05-21 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0002_alter_ao_anh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ao',
            name='anh_lq',
        ),
        migrations.DeleteModel(
            name='LoaiAnh',
        ),
    ]
