# Generated by Django 4.2 on 2023-05-21 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0004_ao_old_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ao',
            name='old_image',
        ),
    ]
