# Generated by Django 4.2 on 2023-05-28 13:56

import USER.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0005_remove_ao_old_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoaiAo',
            fields=[
                ('id_loaiao', models.IntegerField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='ao',
            name='sale_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ao',
            name='type_prodc',
            field=models.IntegerField(default=0, verbose_name=USER.models.LoaiAo),
        ),
    ]
