# Generated by Django 4.2 on 2023-05-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0006_loaiao_ao_sale_price_ao_type_prodc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loaiao',
            name='id_loaiao',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
