# Generated by Django 4.2 on 2023-05-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0007_alter_loaiao_id_loaiao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ao',
            name='sale_price',
            field=models.DecimalField(decimal_places=3, max_digits=30),
        ),
    ]
