# Generated by Django 4.2 on 2023-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0008_alter_ao_sale_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ao_temp',
            fields=[
                ('id_ao', models.IntegerField(primary_key=True, serialize=False)),
                ('ten_ao', models.CharField(max_length=100)),
                ('soluong', models.IntegerField()),
                ('giatien', models.DecimalField(decimal_places=3, max_digits=30)),
                ('anh', models.CharField(max_length=200)),
            ],
        ),
    ]
