# Generated by Django 4.2 on 2023-05-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0009_ao_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ao_temp',
            name='taikhoan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
