# Generated by Django 4.2 on 2023-05-31 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0011_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acc_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
