# Generated by Django 4.2 on 2023-06-02 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0013_alter_account_acc_name_alter_account_email_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ao_temp',
            name='tongtien',
            field=models.IntegerField(default=0),
        ),
    ]
