# Generated by Django 4.2 on 2023-06-02 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0015_ao_favourite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongTinDatHang',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thongtinsanpham', models.CharField(max_length=200)),
                ('tongtien', models.IntegerField()),
                ('dienthoai', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('diachi', models.CharField(max_length=200)),
            ],
        ),
    ]
