# Generated by Django 4.2 on 2023-06-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0016_thongtindathang'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtindathang',
            name='taikhoan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
