# Generated by Django 4.2 on 2023-06-12 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USER', '0017_thongtindathang_taikhoan'),
    ]

    operations = [
        migrations.AddField(
            model_name='thongtindathang',
            name='ten',
            field=models.CharField(default='', max_length=200),
        ),
    ]
